# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.


# @param {String} s
# @param {String} t
# @return {Character}
def find_the_difference(s, t)
  return '' if s.size == t.size
  ('a'..'z').each do |c|
    return c unless s.scan(c).size == t.scan(c).size
  end
  return ''
end